export const en = {
  brand: { name: "Webshop Template", tagline: "Modern reusable commerce engine" },
  nav: { home: "Home", products: "Products", categories: "Categories", cart: "Cart", account: "Account", orders: "Orders", admin: "Admin", login: "Login", logout: "Logout", search: "Search" },
  common: { loading: "Loading...", error: "Something went wrong", retry: "Retry", empty: "Nothing to show yet", details: "Details", addToCart: "Add to cart", checkout: "Checkout", remove: "Remove", delete: "Delete", edit: "Edit", save: "Save", create: "Create", update: "Update", cancel: "Cancel", open: "Open", back: "Back", total: "Total", quantity: "Quantity", price: "Price", status: "Status", actions: "Actions", email: "Email", password: "Password", name: "Name", username: "Username", phone: "Phone", optional: "optional", search: "Search", pcs: "pcs" },
  home: { eyebrow: "Premium webshop template", title: "An elegant base for new commerce projects", lead: "A dark, modern storefront for products, cart, checkout, orders and admin workflows.", primaryCta: "Browse products", secondaryCta: "Admin area", featured: "Featured products", categories: "Categories", benefits: "Benefits", howItWorks: "How it works", newsletter: "Newsletter", newsletterLead: "Get updates about new products and offers.", subscribe: "Subscribe", benefit1: "Fast launch", benefit2: "Secure foundation", benefit3: "Responsive experience", step1: "Choose a product", step2: "Add it to cart", step3: "Place the order" },
  products: { title: "Products", lead: "Browse the webshop catalog.", featured: "Featured", soldOut: "Sold out", chooseOption: "Choose option", noProducts: "No products yet.", searchPlaceholder: "Search products", productDetails: "Product details", option: "Option", stock: "Stock", category: "Category", categoriesLead: "Choose a category and start browsing products from there.", allProducts: "All products" },
  cart: { title: "Cart", empty: "Your cart is empty.", item: "item", clear: "Clear cart", summary: "Cart summary", continueShopping: "Continue shopping" },
  checkout: { title: "Checkout", customer: "Customer details", shipping: "Shipping", payment: "Payment", placeOrder: "Place order", empty: "Your cart is empty, so there is nothing to order.", shippingAddress: "Shipping address", zip: "ZIP", city: "City", address: "Address", pickupPoint: "Pickup point", botCheck: "Bot protection", orderSaved: "Saving order...", fillRequired: "Fill the required fields." },
  auth: { loginTitle: "Login", registerTitle: "Register", intro: "Create an account to manage your profile and orders.", fullName: "Full name", confirmPassword: "Confirm password", currentPassword: "Current password", newPassword: "New password", acceptTerms: "I accept the terms", acceptPrivacy: "I accept the privacy policy", newsletter: "Subscribe to newsletter", forgotPassword: "Forgot password?", noAccount: "No account yet?", hasAccount: "Already have an account?", working: "Working...", requiredError: "Check the required fields and password confirmation.", captchaError: "Complete bot protection before continuing.", loginFailed: "Login failed.", registerFailed: "Registration failed." },
  account: { title: "Account", lead: "Profile, password, newsletter settings and order history.", profile: "Profile", password: "Change password", newsletter: "Newsletter", deleteAccount: "Delete account", myOrders: "My orders", profileSaved: "Profile saved.", passwordSaved: "Password updated.", newsletterSaved: "Newsletter setting saved.", dangerLead: "Deleting your account is permanent." },
  orders: { title: "Orders", lead: "Order history and statuses.", empty: "You do not have orders yet.", orderNumber: "Order number", date: "Date", customer: "Customer", items: "Items" },
  admin: { dashboard: "Admin Dashboard", products: "Admin Products", orders: "Admin Orders", users: "Admin Users", shipping: "Shipping", newsletters: "Newsletters", signedIn: "Signed in", adminLead: "Manage products, orders, users and operational settings.", totalOrders: "Total orders", todayOrders: "Today orders", weekOrders: "Week orders", pendingOrders: "Pending orders", revenue: "Completed revenue", totalUsers: "Users", totalProducts: "Products", lowStock: "Low stock", role: "Role", active: "Active", inactive: "Inactive", deactivate: "Deactivate", activate: "Activate", manageProducts: "Manage generic webshop products.", manageOrders: "Search orders, update statuses and inspect details.", manageUsers: "Manage accounts, roles and active status." },
  states: { loadingProducts: "Loading products...", loadingOrders: "Loading orders...", loadingUsers: "Loading users...", productError: "Products could not be loaded.", orderError: "Orders could not be loaded.", userError: "Users could not be loaded.", adminOnly: "Admin access is required for this page.", notFoundTitle: "Page not found", notFoundLead: "The page you are looking for does not exist or has moved." },
  footer: { text: "A generic modern webshop template built on React and FastAPI.", legal: "Legal", privacy: "Privacy", terms: "Terms", shipping: "Shipping", payment: "Payment" },
  language: { hu: "HU", en: "EN", label: "Language" }
} as const;
