export const hu = {
  brand: { name: "Webshop Template", tagline: "Modern, újrahasznosítható webshop motor" },
  nav: { home: "Főoldal", products: "Termékek", categories: "Kategóriák", cart: "Kosár", account: "Fiókom", orders: "Rendelések", admin: "Admin", login: "Belépés", logout: "Kilépés", search: "Keresés" },
  common: { loading: "Betöltés...", error: "Hiba történt", retry: "Újrapróbálom", empty: "Nincs megjeleníthető adat", details: "Részletek", addToCart: "Kosárba", checkout: "Pénztár", remove: "Törlés", delete: "Törlés", edit: "Szerkesztés", save: "Mentés", create: "Létrehozás", update: "Frissítés", cancel: "Mégse", open: "Megnyitás", back: "Vissza", total: "Összesen", quantity: "Mennyiség", price: "Ár", status: "Státusz", actions: "Műveletek", email: "E-mail", password: "Jelszó", name: "Név", username: "Felhasználónév", phone: "Telefonszám", optional: "opcionális", search: "Keresés", pcs: "db" },
  home: { eyebrow: "Prémium webshop template", title: "Elegáns alap új webshop projektekhez", lead: "Sötét, modern felület termékekhez, kosárhoz, rendeléskezeléshez és admin munkafolyamatokhoz.", primaryCta: "Termékek böngészése", secondaryCta: "Admin felület", featured: "Kiemelt termékek", categories: "Kategóriák", benefits: "Előnyök", howItWorks: "Hogyan működik", newsletter: "Hírlevél", newsletterLead: "Értesülj az újdonságokról és ajánlatokról.", subscribe: "Feliratkozás", benefit1: "Gyors indulás", benefit2: "Biztonságos alapok", benefit3: "Reszponzív felület", step1: "Válassz terméket", step2: "Tedd kosárba", step3: "Add le a rendelést" },
  products: { title: "Termékek", lead: "Böngészd a webshop termékeit.", featured: "Kiemelt", soldOut: "Elfogyott", chooseOption: "Válassz opciót", noProducts: "Még nincsenek termékek.", searchPlaceholder: "Termék keresése", productDetails: "Termék részletei", option: "Opció", stock: "Készlet", category: "Kategória", categoriesLead: "Válassz kategóriát, és indítsd innen a termékböngészést.", allProducts: "Összes termék" },
  cart: { title: "Kosár", empty: "A kosarad még üres.", item: "termék", clear: "Kosár ürítése", summary: "Kosár összesítő", continueShopping: "Vásárlás folytatása" },
  checkout: { title: "Pénztár", customer: "Vásárlói adatok", shipping: "Szállítás", payment: "Fizetés", placeOrder: "Rendelés leadása", empty: "A kosár üres, ezért nincs mit megrendelni.", shippingAddress: "Szállítási cím", zip: "Irányítószám", city: "Város", address: "Cím", pickupPoint: "Átvételi pont", botCheck: "Botvédelem", orderSaved: "Rendelés mentése...", fillRequired: "Töltsd ki a kötelező mezőket." },
  auth: { loginTitle: "Belépés", registerTitle: "Regisztráció", intro: "Hozz létre fiókot a rendeléseid és adataid kezeléséhez.", fullName: "Teljes név", confirmPassword: "Jelszó megerősítése", currentPassword: "Jelenlegi jelszó", newPassword: "Új jelszó", acceptTerms: "Elfogadom az ÁSZF-et", acceptPrivacy: "Elfogadom az adatkezelési tájékoztatót", newsletter: "Feliratkozom a hírlevélre", forgotPassword: "Elfelejtett jelszó?", noAccount: "Nincs fiókod?", hasAccount: "Már van fiókod?", working: "Feldolgozás...", requiredError: "Ellenőrizd a kötelező mezőket és a jelszó megerősítését.", captchaError: "Folytatás előtt teljesítsd a botvédelmi ellenőrzést.", loginFailed: "A belépés nem sikerült.", registerFailed: "A regisztráció nem sikerült." },
  account: { title: "Fiókom", lead: "Profiladatok, jelszó, hírlevél és rendelési előzmények.", profile: "Profil", password: "Jelszó módosítása", newsletter: "Hírlevél", deleteAccount: "Fiók törlése", myOrders: "Rendeléseim", profileSaved: "Profil mentve.", passwordSaved: "Jelszó frissítve.", newsletterSaved: "Hírlevél beállítás mentve.", dangerLead: "A fiók törlése végleges művelet." },
  orders: { title: "Rendelések", lead: "Rendelési előzmények és státuszok.", empty: "Még nincs rendelésed.", orderNumber: "Rendelésszám", date: "Dátum", customer: "Vásárló", items: "Tételek" },
  admin: { dashboard: "Admin vezérlőpult", products: "Admin termékek", orders: "Admin rendelések", users: "Admin felhasználók", shipping: "Szállítás", newsletters: "Hírlevelek", signedIn: "Bejelentkezve", adminLead: "Termékek, rendelések, felhasználók és üzemeltetési beállítások kezelése.", totalOrders: "Összes rendelés", todayOrders: "Mai rendelések", weekOrders: "Heti rendelések", pendingOrders: "Függő rendelések", revenue: "Teljesített bevétel", totalUsers: "Felhasználók", totalProducts: "Termékek", lowStock: "Alacsony készlet", role: "Jogosultság", active: "Aktív", inactive: "Inaktív", deactivate: "Inaktiválás", activate: "Aktiválás", manageProducts: "Általános webshop termékek kezelése.", manageOrders: "Rendelések keresése, státuszok és részletek kezelése.", manageUsers: "Felhasználók, jogosultságok és aktív állapot kezelése." },
  states: { loadingProducts: "Termékek betöltése...", loadingOrders: "Rendelések betöltése...", loadingUsers: "Felhasználók betöltése...", productError: "A termékek betöltése nem sikerült.", orderError: "A rendelések betöltése nem sikerült.", userError: "A felhasználók betöltése nem sikerült.", adminOnly: "Ehhez az oldalhoz admin jogosultság szükséges.", notFoundTitle: "Az oldal nem található", notFoundLead: "A keresett oldal nem létezik vagy áthelyezésre került." },
  footer: { text: "Általános, modern webshop template React és FastAPI alapokon.", legal: "Jogi", privacy: "Adatvédelem", terms: "ÁSZF", shipping: "Szállítás", payment: "Fizetés" },
  language: { hu: "HU", en: "EN", label: "Nyelv" }
} as const;
